In [1]:
import pandas as pd
import numpy as np

In [2]:
label_path = '/mnt/data/Birdman/samples/labels/noise.csv'

In [3]:
start_end_labels = pd.read_csv(label_path)

In [4]:
start_end_labels

                                 File Name  Time Start  Time End  duration
0            STHELENA-02_20140605_200000_1     300.000   340.000      40.0
1            STHELENA-02_20140605_200000_1     545.000   555.000      10.0
2            STHELENA-02_20140605_200000_2     510.000   540.000      30.0
3            STHELENA-02_20140605_200000_4     290.000   300.000      10.0
4            STHELENA-02_20140605_200000_4     410.000   440.000      30.0
5            STHELENA-02_20140605_200000_5     165.000   185.000      20.0
6            STHELENA-02_20140605_200000_5     415.000   455.000      40.0
7            STHELENA-02_20140605_200000_6      10.000    20.000      10.0
8            STHELENA-02_20140605_200000_8     510.000   550.000      40.0
9           STHELENA-02_20140605_200000_10     120.000   240.000     120.0
10          STHELENA-02_20140605_200000_11     230.000   290.000      60.0
11          STHELENA-02_20140605_200000_12     380.000   410.000      30.0
12     STHELENA-01_20140106_210000_0-15min       0.000   840.000     840.0
13  STHELENA-02_20140108_210100_110-120min       0.000   600.000     600.0
14   STHELENA-01_20140101_210000_55-105min       0.000   600.000     600.0
15           STHELENA-02_20140605_200000_2      70.132    70.932       NaN
16           STHELENA-02_20140605_200000_2      70.532    71.332       NaN

In [7]:
split = []

for index, row in start_end_labels.iterrows():
    split_len = 1.0
    filename = row['File Name']
    timestart = row['Time Start']
    timeend = row['Time End']
    timestart_sliced = np.arange(timestart, timeend, split_len) 
    timeend_sliced = np.arange(timestart + split_len, timeend + split_len, split_len)
    df = pd.DataFrame(data={'start': timestart_sliced, 'end': timeend_sliced})
    df['sound.files'] = filename
    split.append(df)

In [19]:
df = pd.concat(split, ignore_index=True)
df = df.rename(columns={'index': 'selec', 'Time Start': 'start', 'Time End': 'end'}).reset_index()

In [22]:
df.to_csv('noiseR.csv', index=False)

In [21]:
df.head(50)

    index  start    end                    sound.files
0       0  300.0  301.0  STHELENA-02_20140605_200000_1
1       1  301.0  302.0  STHELENA-02_20140605_200000_1
2       2  302.0  303.0  STHELENA-02_20140605_200000_1
3       3  303.0  304.0  STHELENA-02_20140605_200000_1
4       4  304.0  305.0  STHELENA-02_20140605_200000_1
5       5  305.0  306.0  STHELENA-02_20140605_200000_1
6       6  306.0  307.0  STHELENA-02_20140605_200000_1
7       7  307.0  308.0  STHELENA-02_20140605_200000_1
8       8  308.0  309.0  STHELENA-02_20140605_200000_1
9       9  309.0  310.0  STHELENA-02_20140605_200000_1
10     10  310.0  311.0  STHELENA-02_20140605_200000_1
11     11  311.0  312.0  STHELENA-02_20140605_200000_1
12     12  312.0  313.0  STHELENA-02_20140605_200000_1
13     13  313.0  314.0  STHELENA-02_20140605_200000_1
14     14  314.0  315.0  STHELENA-02_20140605_200000_1
15     15  315.0  316.0  STHELENA-02_20140605_200000_1
16     16  316.0  317.0  STHELENA-02_20140605_200000_1
17     17  317.0  318.0  STHELENA-02_20140605_200000_1
18     18  318.0  319.0  STHELENA-02_20140605_200000_1
19     19  319.0  320.0  STHELENA-02_20140605_200000_1
20     20  320.0  321.0  STHELENA-02_20140605_200000_1
21     21  321.0  322.0  STHELENA-02_20140605_200000_1
22     22  322.0  323.0  STHELENA-02_20140605_200000_1
23     23  323.0  324.0  STHELENA-02_20140605_200000_1
24     24  324.0  325.0  STHELENA-02_20140605_200000_1
25     25  325.0  326.0  STHELENA-02_20140605_200000_1
26     26  326.0  327.0  STHELENA-02_20140605_200000_1
27     27  327.0  328.0  STHELENA-02_20140605_200000_1
28     28  328.0  329.0  STHELENA-02_20140605_200000_1
29     29  329.0  330.0  STHELENA-02_20140605_200000_1
30     30  330.0  331.0  STHELENA-02_20140605_200000_1
31     31  331.0  332.0  STHELENA-02_20140605_200000_1
32     32  332.0  333.0  STHELENA-02_20140605_200000_1
33     33  333.0  334.0  STHELENA-02_20140605_200000_1
34     34  334.0  335.0  STHELENA-02_20140605_200000_1
35     35  335.0  336.0  STHELENA-02_20140605_200000_1
36     36  336.0  337.0  STHELENA-02_20140605_200000_1
37     37  337.0  338.0  STHELENA-02_20140605_200000_1
38     38  338.0  339.0  STHELENA-02_20140605_200000_1
39     39  339.0  340.0  STHELENA-02_20140605_200000_1
40     40  545.0  546.0  STHELENA-02_20140605_200000_1
41     41  546.0  547.0  STHELENA-02_20140605_200000_1
42     42  547.0  548.0  STHELENA-02_20140605_200000_1
43     43  548.0  549.0  STHELENA-02_20140605_200000_1
44     44  549.0  550.0  STHELENA-02_20140605_200000_1
45     45  550.0  551.0  STHELENA-02_20140605_200000_1
46     46  551.0  552.0  STHELENA-02_20140605_200000_1
47     47  552.0  553.0  STHELENA-02_20140605_200000_1
48     48  553.0  554.0  STHELENA-02_20140605_200000_1
49     49  554.0  555.0  STHELENA-02_20140605_200000_1